# Generated by Django 5.1.4 on 2024-12-09 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=255, verbose_name='Address')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP Address')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='devices_app.devicemodel', verbose_name='Model')),
            ],
        ),
    ]
